### ISSUE TITLE
Panic with v0.1.3

### ISSUE THREAD

**Issue by sylr** [Comcast/trickster#105]
Hi,

I installed v0.1.3 in order to see if it fixes https://github.com/Comcast/trickster/issues/92 but I encountered this.

```
panic: runtime error: index out of range
goroutine 493 [running]:
main.(*PrometheusMatrixEnvelope).cropToRange(0xc0001c06f8, 0x5c06535c, 0x0)
	/go/src/github.com/Comcast/trickster/handlers.go:1014 +0x4ee
main.(*TricksterHandler).originRangeProxyHandler(0xc000062140, 0xc000312640, 0x41, 0xc00014c8a0)
	/go/src/github.com/Comcast/trickster/handlers.go:840 +0x615
created by main.(*TricksterHandler).queueRangeProxyRequest
	/go/src/github.com/Comcast/trickster/handlers.go:660 +0x276
```

**Comment by sylr** [comment]
I believe this has been introduced by https://github.com/Comcast/trickster/commit/733c75d1ca1fa3ab911b676398aa01b90509bef3

cc @jacksontj

**Comment by jranson** [comment]
Hey @sylr are you able to reproduce the panic with a sharable query (e.g., one of the `go_` metric names)?  Thanks!

**Comment by sylr** [comment]
Yes `go_gc_duration_seconds{}` made trickster crash

```time=2018-12-05T16:00:22.495898239Z app=trickster caller=trickster/main.go:63 level=info event="application startup" version=0.1.3
time=2018-12-05T16:00:22.496136741Z app=trickster caller=trickster/memory.go:39 level=info event="memorycache setup"
time=2018-12-05T16:00:22.496278442Z app=trickster caller=trickster/metrics.go:47 level=info event="metrics http endpoint starting" address= port=8082
time=2018-12-05T16:00:22.496460743Z app=trickster caller=trickster/main.go:94 level=info event="proxy http endpoint starting" address= port=9090
time=2018-12-05T16:01:00.697780484Z app=trickster caller=trickster/handlers.go:657 level=info event="starting originRangeProxyHandler" cacheKey=7afae6d6003a8f4b6146473157961ddb.8c8344bd560f535d275ce293ffa59420
panic: runtime error: index out of range

goroutine 15 [running]:
main.(*PrometheusMatrixEnvelope).cropToRange(0xc00016ab78, 0x5c06a4bc, 0x0)
        /go/src/github.com/Comcast/trickster/handlers.go:1014 +0x4ee
main.(*TricksterHandler).originRangeProxyHandler(0xc000062100, 0xc000025f90, 0x41, 0xc000066de0)
        /go/src/github.com/Comcast/trickster/handlers.go:840 +0x615
created by main.(*TricksterHandler).queueRangeProxyRequest
        /go/src/github.com/Comcast/trickster/handlers.go:660 +0x276
```

**Comment by jranson** [comment]
Thanks. Sorry to belabor - any chance you can go to debug logging and provide some urls. That way we can determine out the nature and scope of the defect. Thanks again for your help and for the report!

**Comment by sylr** [comment]
My configuration

```[main]
# instance_id allows you to run multiple trickster processes on the same host and log to separate files
# Useful for baremetal, not so much for elastic deployments, so only uncomment if you really need it
#instance_id = 1

# Configuration options for the Proxy Server
[proxy_server]
# listen_port defines the port on which Trickster's Proxy server listens.
# since this is a proxy for Prometheus, we use 9090 by default, just like Prometheus does
# listen_port = 9090
# listen_address defines the ip on which Trickster's Proxy server listens.
# empty by default, listening on all interfaces
# listen_address =

[cache]
# cache_type defines what kind of cache Trickster uses
# options are 'boltdb', 'filesystem', 'memory', and 'redis'.
# The default is 'memory'.
cache_type = 'memory'

# record_ttl_secs defines the relative expiration of cached queries. default is 6 hours (21600 seconds)
# record_ttl_secs = 21600

# reap_sleep_ms defines how long the cache reaper waits between reap cycles. Default is 1000 (1s)
# reap_sleep_ms = 1000

# compression determines whether the cache should be compressed. default is true
# compression = true

    ### Configuration options when using a Redis Cache
    # [cache.redis]
    # protocol defines the protocol for connecting to redis ('unix' or 'tcp') 'tcp' is default
    # protocol = 'tcp'
    # endpoint defines the fqdn+port or path to a unix socket file for connecting to redis
    # default is 'redis:6379'
    # endpoint = 'redis:6379'

    ### Configuration options when using a Filesystem Cache
    # [cache.filesystem]
    # cache_path defines the directory location under which the Trickster cache will be maintained
    # default is '/tmp/trickster'
    # cache_path = '/tmp/trickster'

    # Configuration options when using a BoltDb Cache
    #[cache.boltdb]

    # filename defines the file where the Trickster cache will be maintained
    # default is 'trickster.db'
    # filename = 'trickster.db'

    # bucket defines the name of the BotlDb bucket (similar to a namespace) under which our key value store lives
    # default is 'trickster'
    # bucket = 'trickster'

# Configuration options for mapping Origin(s)
[origins]
    ### The default origin
    [origins.default]

    # origin_url defines the URL of the origin. Default is http://prometheus:9090
    origin_url = 'http://prometheus-thanos-query.monitoring.svc.cluster.local:9090'

    # api path defines the path of the Prometheus API (usually '/api/v1')
    api_path = '/api/v1'

    # default_step defines the step (in seconds) of a query_range request if one is
    # not provided by the client. This helps to correct improperly formed client requests.
    default_step = 30

    # ignore_no_cache_header disables a client's ability to send a no-cache to refresh a cached query. Default is false
    # ignore_no_cache_header = false

    # max_value_age_secs defines the maximum age of specific datapoints in seconds. Default is 86400 (24 hours)
    max_value_age_secs = 86400

    # fast_forward_disable, when set to true, will turn off the 'fast forward' feature for any requests proxied to this origin
    fast_forward_disable = true

    # For multi-origin support, origins are named, and the name is the second word of the configuration section name.
    # In this example, an origin is named "foo". Clients can indicate this origin in their path (http://trickster.example.com:9090/foo/query_range?.....)
    # there are other ways for clients to indicate which origin to use in a multi-origin setup. See the documentation for more information

    # [origins.foo]
    # origin_url = 'http://prometheus-foo:9090'
    # api_path = '/api/v1'
    # default_step = 300
    # ignore_no_cache_header = false
    # max_value_age_secs = 86400

# Configuration Options for Metrics Instrumentation
[metrics]
# listen_port defines the port that Trickster's metrics server listens on at /metrics
listen_port = 8082
# listen_address defines the ip that Trickster's metrics server listens on at /metrics
# empty by default, listening on all interfaces
# listen_address =

# Configuration Options for Logging Instrumentation
[logging]
# log_level defines the verbosity of the logger. Possible values are 'debug', 'info', 'warn', 'error'
# default is info
log_level = 'info'

# log_file defines the file location to store logs. These will be auto-rolled and maintained for you.
# not specifying a log_file (this is the default behavior) will print logs to STDOUT
# log_file = '/some/path/to/trickster.log'
```

The most notable thing is the fast forward turned off.

**Comment by sylr** [comment]
```
time=2018-12-05T16:09:43.448445101Z app=trickster caller=trickster/main.go:63 level=info event="application startup" version=0.1.3
time=2018-12-05T16:09:43.4485415Z app=trickster caller=trickster/memory.go:39 level=info event="memorycache setup"
time=2018-12-05T16:09:43.4488054Z app=trickster caller=trickster/main.go:94 level=info event="proxy http endpoint starting" address= port=9090
time=2018-12-05T16:09:43.4489277Z app=trickster caller=trickster/metrics.go:47 level=info event="metrics http endpoint starting" address= port=8082
time=2018-12-05T16:10:00.666040994Z app=trickster caller=trickster/handlers.go:657 level=info event="starting originRangeProxyHandler" cacheKey=7afae6d6003a8f4b6146473157961ddb.8c8344bd560f535d275ce293ffa59420
time=2018-12-05T16:10:04.061612392Z app=trickster caller=trickster/handlers.go:312 level=debug event=prometheusOriginHttpRequest url="http://prometheus-thanos-query.monitoring.svc.cluster.local:9090/api/v1/query_range?end=1544026200&query=go_gc_duration_seconds&start=1544004600&step=30&timeout=60s" duration=3.395322898s
panic: runtime error: index out of range

goroutine 52 [running]:
main.(*PrometheusMatrixEnvelope).cropToRange(0xc0001fa938, 0x5c06a6d8, 0x0)
        /go/src/github.com/Comcast/trickster/handlers.go:1014 +0x4ee
main.(*TricksterHandler).originRangeProxyHandler(0xc0000ba700, 0xc0002100f0, 0x41, 0xc0001de120)
        /go/src/github.com/Comcast/trickster/handlers.go:840 +0x615
created by main.(*TricksterHandler).queueRangeProxyRequest
        /go/src/github.com/Comcast/trickster/handlers.go:660 +0x276
```

**Comment by jacksontj** [comment]
#107 has a test which repros this panic and a fix. Thanks for catching that @sylr. I wasn't able to repro it myself, but from the repro case I have it seems that the issue's cause is that prometheus is returning a result without values -- which trickster wasn't handling properly (more details in the PR and commit messages).

**Comment by jranson** [comment]
@sylr 0.1.4 is released w/ patch from @jacksontj   can you let us know how this works out on this issue as well as #92 ? Thank you all!

**Comment by sylr** [comment]
Still crashing:

```
time=2018-12-06T08:03:17.114468341Z app=trickster caller=trickster/main.go:63 level=info event="application startup" version=0.1.4
time=2018-12-06T08:03:17.114571441Z app=trickster caller=trickster/memory.go:39 level=info event="memorycache setup"
time=2018-12-06T08:03:17.114880141Z app=trickster caller=trickster/main.go:94 level=info event="proxy http endpoint starting" address= port=9090
time=2018-12-06T08:03:17.115143241Z app=trickster caller=trickster/metrics.go:47 level=info event="metrics http endpoint starting" address= port=8082
sylvain@ubuntu-1604-dev:~/git/k8s-conf[master]$ kubectl --context=k8s2-euw-infra --namespace=monitoring logs trickster-thanos-f96fcfc95-7cx6g -f
time=2018-12-06T08:03:17.114468341Z app=trickster caller=trickster/main.go:63 level=info event="application startup" version=0.1.4
time=2018-12-06T08:03:17.114571441Z app=trickster caller=trickster/memory.go:39 level=info event="memorycache setup"
time=2018-12-06T08:03:17.114880141Z app=trickster caller=trickster/main.go:94 level=info event="proxy http endpoint starting" address= port=9090
time=2018-12-06T08:03:17.115143241Z app=trickster caller=trickster/metrics.go:47 level=info event="metrics http endpoint starting" address= port=8082















time=2018-12-06T08:03:40.866404871Z app=trickster caller=trickster/handlers.go:657 level=info event="starting originRangeProxyHandler" cacheKey=7afae6d6003a8f4b6146473157961ddb.255457796f081fcb0178911ec34de9a2
time=2018-12-06T08:03:40.86929357Z app=trickster caller=trickster/handlers.go:657 level=info event="starting originRangeProxyHandler" cacheKey=cab9326e296ab21742c2a1b0722bea75.19152cb8693bdf61ff47f07196adff46
time=2018-12-06T08:03:40.875677369Z app=trickster caller=trickster/handlers.go:657 level=info event="starting originRangeProxyHandler" cacheKey=cab9326e296ab21742c2a1b0722bea75.18b714de8a5cbf4ce63858c9d592eb63
time=2018-12-06T08:03:40.876284969Z app=trickster caller=trickster/handlers.go:657 level=info event="starting originRangeProxyHandler" cacheKey=cab9326e296ab21742c2a1b0722bea75.d2b5a680f83a63a582f1387bccda50e9
time=2018-12-06T08:03:40.891302467Z app=trickster caller=trickster/handlers.go:657 level=info event="starting originRangeProxyHandler" cacheKey=cab9326e296ab21742c2a1b0722bea75.96b6ab681c9291c174d103c2ad6a4576
time=2018-12-06T08:03:40.892179167Z app=trickster caller=trickster/handlers.go:657 level=info event="starting originRangeProxyHandler" cacheKey=7afae6d6003a8f4b6146473157961ddb.cdc7a6badf9c2b26efa516d8efcc3782
time=2018-12-06T08:03:40.903185665Z app=trickster caller=trickster/handlers.go:657 level=info event="starting originRangeProxyHandler" cacheKey=cab9326e296ab21742c2a1b0722bea75.8558f221ed7ec3b674216b32cb49430a
time=2018-12-06T08:03:40.903455265Z app=trickster caller=trickster/handlers.go:657 level=info event="starting originRangeProxyHandler" cacheKey=cab9326e296ab21742c2a1b0722bea75.4659756fa1f4f998f73f89773508e632
time=2018-12-06T08:03:40.903538765Z app=trickster caller=trickster/handlers.go:657 level=info event="starting originRangeProxyHandler" cacheKey=7afae6d6003a8f4b6146473157961ddb.0572566739b6e12f13f3a95eb4ab7fc7
time=2018-12-06T08:03:40.903680565Z app=trickster caller=trickster/handlers.go:657 level=info event="starting originRangeProxyHandler" cacheKey=7afae6d6003a8f4b6146473157961ddb.8c9b45ab6d2d63aba6fc21a0e5009c52
time=2018-12-06T08:03:40.907453964Z app=trickster caller=trickster/handlers.go:657 level=info event="starting originRangeProxyHandler" cacheKey=7afae6d6003a8f4b6146473157961ddb.bc28e083db58c2f0a00e5d92a12a5c31
time=2018-12-06T08:03:40.914812563Z app=trickster caller=trickster/handlers.go:657 level=info event="starting originRangeProxyHandler" cacheKey=cab9326e296ab21742c2a1b0722bea75.012e5b45cc2590fcdc240090e3f19a31
time=2018-12-06T08:03:40.914862663Z app=trickster caller=trickster/handlers.go:657 level=info event="starting originRangeProxyHandler" cacheKey=7afae6d6003a8f4b6146473157961ddb.6d2efcbe2ca733c3084a01e160cb524c
panic: runtime error: index out of range

goroutine 156 [running]:
main.(*PrometheusMatrixEnvelope).cropToRange(0xc0005126f8, 0x5c07865c, 0x0)
        /go/src/github.com/Comcast/trickster/handlers.go:1035 +0x4ee
main.(*TricksterHandler).originRangeProxyHandler(0xc000178000, 0xc000566050, 0x41, 0xc0000673e0)
        /go/src/github.com/Comcast/trickster/handlers.go:860 +0x6b4
created by main.(*TricksterHandler).queueRangeProxyRequest
        /go/src/github.com/Comcast/trickster/handlers.go:660 +0x276
```

**Comment by jacksontj** [comment]
@sylr thanks for the catch! You are correct, that is incorrect. I have added a test case and a fix in #108

**Comment by sylr** [comment]
I'd need a docker image hosted somewhere to test your new patch.

**Comment by SuperQ** [comment]
I deployed the patch to our instance, seems to be more stable. I'll give it a few more hours to see if it stays up.

**Comment by jranson** [comment]
@sylr would you mind trying with tricksterio/trickster:0.1.5-test ?   That includes @jacksontj's fix. Thanks!

**Comment by sylr** [comment]
@jranson on it

**Comment by sylr** [comment]
Seems OK now :+1:

**Comment by jranson** [comment]
Awesome, thanks for checking. Sorry for the wild ride :) I'll let it burn in with both you and @SuperQ, for a few more hours and then merge/cut the official release.

**Comment by sylr** [comment]
No worries, happy to help, `Trickster` is a great addition to our setup.

**Comment by SuperQ** [comment]
Confirmed, no crashes since pushing the patched version.
