### ISSUE TITLE
Panic after upgrade to 1.0-beta

### ISSUE THREAD

**Issue by ese** [Comcast/trickster#178]
After upgrade to test 1.0-beta I got this panic:

```
time=2019-04-01T15:13:28.954478674Z app=trickster caller=trickster/main.go:54 level=info event="application start up" name=trickster version=1.0.0
time=2019-04-01T15:13:28.954590951Z app=trickster caller=cache/memory/memory.go:40 level=info event="memorycache setup"
time=2019-04-01T15:13:28.954636574Z app=trickster caller=routing/registration/registration.go:44 level=info event="Registering Prometheus Route Paths" originName=default upstreamHost=localhost:10902
time=2019-04-01T15:13:28.954685424Z app=trickster caller=util/metrics/metrics.go:184 level=info event="metrics http endpoint starting" address= port=8082
time=2019-04-01T15:13:28.954790933Z app=trickster caller=trickster/main.go:61 level=info event="proxy http endpoint starting" address= port=9090
panic: runtime error: index out of range

goroutine 106 [running]:
github.com/Comcast/trickster/internal/proxy.FetchViaObjectProxyCache(0xc0001261c0, 0xae9360, 0xc000134b60, 0xae4fe0, 0xc000142690, 0xf, 0xae0100, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/Comcast/trickster/internal/proxy/objectproxycache.go:37 +0xad3
github.com/Comcast/trickster/internal/proxy.DeltaProxyCacheRequest.func2(0xc0003ef260, 0xc000458070, 0xc00011a280, 0xae9360, 0xc000134b60, 0xae4fe0, 0xc000142690, 0xc0003e9b50, 0xc00010a270, 0xc0001074d0)
	/go/src/github.com/Comcast/trickster/internal/proxy/deltaproxycache.go:175 +0x106
created by github.com/Comcast/trickster/internal/proxy.DeltaProxyCacheRequest
	/go/src/github.com/Comcast/trickster/internal/proxy/deltaproxycache.go:171 +0x139c
```

Using: tricksterio/trickster:1.0-beta
prometheus: thanos-querier 0.3.2

Tested with default config changing only host of the prometheus.
Previous versions of trickster worked fine

Some queries seems to work and others ends on this panic. I can't see a pattern here

**Comment by jranson** [comment]
@ese It looks like it is panicking while trying to handle Authorization headers. So just to check: are you using auth with your Prometheus, and if so, how is that setup (e.g., Basic auth, etc)?  I can setup a similar test harness to reproduce the condition.

**Comment by jranson** [comment]
@ese I've made some adjustments and pushed an updated `tricksterio/trickster:1.0-beta` docker image to address this condition. You'll need to re-pull that image, or use `tricksterio/trickster:1.0-beta2`. Thanks for trying out the beta and reporting an issue. Hopefully this resolves it!

**Comment by ese** [comment]
That new release fix the problem. Thanks!
