### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by sylr** [Comcast/trickster#273]
Found on next branch @ 47bb9ff

```
2019/08/27 08:51:00 http: panic serving 10.199.5.148:56360: runtime error: makeslice: cap out of range
goroutine 35294035 [running]:
net/http.(*conn).serve.func1(0xc00021a460)
        /usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x9e5fa0, 0xb5c940)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/Comcast/trickster/internal/timeseries.(*TimeRangeQuery).CalculateDeltas(0xc0001f22d0, 0xc000194240, 0x2, 0x4, 0xb7de60, 0xc00a68fda0, 0x0)
        /go/src/github.com/Comcast/trickster/internal/timeseries/timerangequery.go:48 +0xda
github.com/Comcast/trickster/internal/proxy/engines.DeltaProxyCacheRequest(0xc00cbb3b80, 0xb73440, 0xc0001f2230, 0xb7e8e0, 0xc00017a6e0, 0xb7ad00, 0xc00017a640, 0x13a52453c000)
        /go/src/github.com/Comcast/trickster/internal/proxy/engines/deltaproxycache.go:129 +0x1cf1
github.com/Comcast/trickster/internal/proxy/origins/prometheus.(*Client).QueryRangeHandler(0xc00017a6e0, 0xb73440, 0xc0001f2230, 0xc007f07100)
        /go/src/github.com/Comcast/trickster/internal/proxy/origins/prometheus/handler_query_range.go:26 +0x2d7
net/http.HandlerFunc.ServeHTTP(0xc0001cdb80, 0xb73440, 0xc0001f2230, 0xc007f07100)
        /usr/local/go/src/net/http/server.go:1995 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001940c0, 0xb73440, 0xc0001f2230, 0xc007f06e00)
        /go/pkg/mod/github.com/gorilla/mux@v1.7.1/mux.go:212 +0xe3
github.com/gorilla/handlers.CompressHandlerLevel.func1(0xb73a80, 0xc000198380, 0xc007f06e00)
        /go/pkg/mod/github.com/gorilla/handlers@v1.4.0/compress.go:146 +0x1aa
net/http.HandlerFunc.ServeHTTP(0xc000250040, 0xb73a80, 0xc000198380, 0xc007f06e00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
net/http.serverHandler.ServeHTTP(0xc00016aa90, 0xb73a80, 0xc000198380, 0xc007f06e00)
        /usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00021a460, 0xb753c0, 0xc00447d840)
        /usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2884 +0x2f4
```

**Comment by jranson** [comment]
I have this one patched up and will be part of the next beta release. Thanks for reporting it!

**Comment by jranson** [comment]
@sylr beta10 is released with the fix for this panic. Thanks again for your patience!
