### ISSUE TITLE
http: panic - runtime error: invalid memory address or nil pointe r dereference

### ISSUE THREAD

**Issue by SuperQ** [Comcast/trickster#49]
I built against latest master, I get a number of panics.

```
2018-06-04_15:06:41.51609 time=2018-06-04T15:06:41.515986593Z app=trickster caller=trickster/handlers.go:238 level=error event="error downloading url" url="http://10.62.0.10:9090/api/v1/series?end=1528124772&match%5B%5D=job_queue_duration_seconds_sum&start=1528113972" detail="Get http://10.62.0.10:9090/api/v1/series?end=1528124772&match%5B%5D=job_queue_duration_seconds_sum&start=1528113972: dial tcp 10.62.0.10:9090: i/o timeout"
2018-06-04_15:06:41.51642 2018/06/04 15:06:41 http: panic serving 127.0.0.1:37340: runtime error: invalid memory address or nil pointer dereference
2018-06-04_15:06:41.51644 goroutine 7001 [running]:
2018-06-04_15:06:41.51645 net/http.(*conn).serve.func1(0xc4323437c0)
2018-06-04_15:06:41.51645       /usr/local/go-1.10.2/src/net/http/server.go:1726 +0xd0
2018-06-04_15:06:41.51646 panic(0x836d20, 0xb5db60)
2018-06-04_15:06:41.51646       /usr/local/go-1.10.2/src/runtime/panic.go:502 +0x229
2018-06-04_15:06:41.51647 main.writeResponse(0x913580, 0xc42d8e5590, 0xb87e80, 0x0, 0x0, 0x0)
2018-06-04_15:06:41.51647       /home/ben/go/src/github.com/comcast/trickster/handlers.go:551 +0x3e
2018-06-04_15:06:41.51648 main.(*TricksterHandler).promAPIProxyHandler(0xc4200220c0, 0x913580, 0xc42d8e5590, 0xc42e68b400)
2018-06-04_15:06:41.51648       /home/ben/go/src/github.com/comcast/trickster/handlers.go:109 +0x22c
2018-06-04_15:06:41.51649 main.(*TricksterHandler).(main.promAPIProxyHandler)-fm(0x913580, 0xc42d8e5590, 0xc42e68b400)
2018-06-04_15:06:41.51649       /home/ben/go/src/github.com/comcast/trickster/main.go:71 +0x48
2018-06-04_15:06:41.51650 net/http.HandlerFunc.ServeHTTP(0xc4201b3010, 0x913580, 0xc42d8e5590, 0xc42e68b400)
2018-06-04_15:06:41.51650       /usr/local/go-1.10.2/src/net/http/server.go:1947 +0x44
2018-06-04_15:06:41.51651 github.com/gorilla/mux.(*Router).ServeHTTP(0xc420181260, 0x913580, 0xc42d8e5590, 0xc42e68b400)
2018-06-04_15:06:41.51651       /home/ben/go/src/github.com/gorilla/mux/mux.go:162 +0xed
2018-06-04_15:06:41.51653 github.com/gorilla/handlers.CompressHandlerLevel.func1(0x913b40, 0xc42998f6c0, 0xc42e68b200)
2018-06-04_15:06:41.51656       /home/ben/go/src/github.com/gorilla/handlers/compress.go:146 +0x458
2018-06-04_15:06:41.51656 net/http.HandlerFunc.ServeHTTP(0xc42000df20, 0x913b40, 0xc42998f6c0, 0xc42e68b200)
2018-06-04_15:06:41.51657       /usr/local/go-1.10.2/src/net/http/server.go:1947 +0x44
2018-06-04_15:06:41.51657 net/http.serverHandler.ServeHTTP(0xc42017e750, 0x913b40, 0xc42998f6c0, 0xc42e68b200)
2018-06-04_15:06:41.51658       /usr/local/go-1.10.2/src/net/http/server.go:2694 +0xbc
2018-06-04_15:06:41.51658 net/http.(*conn).serve(0xc4323437c0, 0x914280, 0xc42e686e00)
2018-06-04_15:06:41.51659       /usr/local/go-1.10.2/src/net/http/server.go:1830 +0x651
2018-06-04_15:06:41.51659 created by net/http.(*Server).Serve
2018-06-04_15:06:41.51660       /usr/local/go-1.10.2/src/net/http/server.go:2795 +0x27b
```

**Comment by jranson** [comment]
@SuperQ Thanks Ben, we'll take a look at this!

**Comment by SuperQ** [comment]
FYI, @juliusv and I are looking at the `getURL()` function as a source of these errors. We have some ideas, but just wanted to make sure we were not duplicating effort.

**Comment by jranson** [comment]
@SuperQ Sure thing, I just assigned the issue to you. Thank you! My hope is that as we add support for more upstream origin types, that we can keep this method generic enough to work for all of them, so any resiliency we can add would be great!

**Comment by SuperQ** [comment]
What we've discovered so far is that handling the return is fragile, because it doesn't explicitly pass an error back. This seems to be intertwined a bit with the go-kit style structured logging.

One idea I had was that instead of returning the `*http.Response` from `getURL()`, we return `(body []byte, duration time.Duration, err error)`. This would make it easier for functions that use it to know more easily if the URL body results are valid.

**Comment by juliusv** [comment]
Yeah, it should definitely return a proper Go error instead of relying on `nil` check, and I believe generally the best practice is also to log errors at the top of your call stack (in this case, the HTTP handler function) instead of at the bottom. That's in conflict with the structured logging though, as AFAIK there's no corresponding structured error types. So if we want to pass proper errors all the way to the top, they'd probably end up being flattened into a single error string, unless we use some custom error type throughout that preserves key=value structure.

**Comment by juliusv** [comment]
@jranson I just discussed this with go-kit people (Peter and Chris) and while there have been proposals to add key=value contexts to error types (like in https://github.com/pkg/errors/issues/34#issuecomment-225921170), this feature hasn't been added to common error handling libraries yet.

We have three options here as I see it:

a) Create a custom error type that can retain key=value context so that we can log all the structure at the top level.
b) Keep the logging where it currently is.
c) Do logging at the top level, but just live with flattened-out errors being passed to that top level and losing some structure.

IMO a) is a bit overkill and unusual, while b) prevents us from doing proper and explicit error handling by upper layers (one definite rule is that one should either log or return an error, but not both). So IMO c) would be the least bad solution. What do you think?

**Comment by jranson** [comment]
@juliusv @SuperQ Agree C sounds like the best approach for now. In the 10 weeks from inception to open sourcing, I put a lot of work into making sure Trickster works pretty swell when things go right, so I appreciate so much all the effort both of you put in to making it more resilient when things go _wrong_. Thank you so much (and @ChrisHines for the solid advice).

**Comment by juliusv** [comment]
@jranson Thanks. Great, will do that then.

**Comment by ChrisHines** [comment]
@juliusv The current `Log` calls are structured as follows:
```go
level.Error(t.Logger).Log(lfEvent, "error parsing url", "url", uri, lfDetail, err.Error())
```
Breaking that down, it logs:

1. An event describing the action the code was attempting when the error occurred.
2. The value of `uri` passed to `getURL`.
3. The error message.

Notable, the code that calls `getURL` also has access to the value of `uri`. It is also fairly common in go to wrap errors with more detail about the action that returned the error in the fashion of `fmt.Errorf("action: %v", err)`.

So a middle ground here is to add the action context to the error as it bubbles up and let the caller add the uri keyval when it logs the error at the top.

**Comment by SuperQ** [comment]
@jranson Happy to help, I deployed Trickster to [monitor.gitlab.net](https://monitor.gitlab.net) as it was getting completely slammed with traffic.  When the Prometheuses behind the dashboard got overloaded, all kinds of crazy happened. But having it in front has helped a ton.

**Comment by juliusv** [comment]
@jranson While trying to make changes, I couldn't help but notice that Trickster's behavior in the face of partial failures is fuzzy, so I would like to establish what the right thing to do would be in those cases.

For example:

- When we encounter a cache hit, we still try to fetch the most recent new data for the request from Prometheus, but then if that additional request fails, we just ignore that failure and act to the user as if everything was fine: https://github.com/Comcast/trickster/blob/3b4b61ef4117c7928dad7284b83557ff45f27ecc/handlers.go#L534-L538
- In https://github.com/Comcast/trickster/blob/3b4b61ef4117c7928dad7284b83557ff45f27ecc/handlers.go#L579, we sorta kinda track the success of multiple conditional and parallel HTTP requests to Prometheus (only via HTTP response codes, not connection `err`-type errors), merge in the data for those that succeeded, but again act to the user like everything was fine no matter how many partial failures there were.
- There's undhandled non-HTTP failures too, like when we fail to marshal the response matrix, we just log an error, but respond with the incorrectly marshaled result anyway: https://github.com/Comcast/trickster/blob/3b4b61ef4117c7928dad7284b83557ff45f27ecc/handlers.go#L750-L754
- There's of course also the case of outright connection failures where the returned response is `nil` or otherwise defunct, and thus leads to crashes like this one.

I would propose as a first step to make Trickster fail hard when *any* error occurs during the processing of a request that will lead to missing or incorrect data (so most errors). What do you think?

**Comment by juliusv** [comment]
Here's a PR that fixes a lot of crashes and unhandled errors: https://github.com/Comcast/trickster/pull/58

The current strategy is just to fail hard if anything goes wrong, as that's better than the current state and handling partial errors is a tricky issue.
